config/routes.rb
Rails.application.routes.draw do
  resources :posisis
  resources :pendidikans
  resources :karyawans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/karyawan.rb
class Karyawan < ApplicationRecord
    belongs_to :posisi
    belongs_to :pendidikan
end

app/models/pendidikan.rb
class Pendidikan < ApplicationRecord
    has_one :karyawan
end

app/models/posisi.rb
class Posisi < ApplicationRecord
    has_one :karyawan
end
    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/karyawans_controller.rb
class KaryawansController < ApplicationController
  before_action :set_karyawan, only: [:show, :edit, :update, :destroy]

  # GET /karyawans
  # GET /karyawans.json
  def index
    @karyawans = Karyawan.all
  end

  # GET /karyawans/1
  # GET /karyawans/1.json
  def show
  end

  # GET /karyawans/new
  def new
    @karyawan = Karyawan.new
    @pendidikan = Pendidikan.new
  end

  # GET /karyawans/1/edit
  def edit
  end

  # POST /karyawans
  # POST /karyawans.json
  def create
    @karyawan = Karyawan.new(karyawan_params)
   

    respond_to do |format|
      if @karyawan.save
        format.html { redirect_to @karyawan, notice: 'Karyawan was successfully created.' }
        format.json { render :show, status: :created, location: @karyawan }
      else
        format.html { render :new }
        format.json { render json: @karyawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /karyawans/1
  # PATCH/PUT /karyawans/1.json
  def update
    respond_to do |format|
      if @karyawan.update(karyawan_params)
        format.html { redirect_to @karyawan, notice: 'Karyawan was successfully updated.' }
        format.json { render :show, status: :ok, location: @karyawan }
      else
        format.html { render :edit }
        format.json { render json: @karyawan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /karyawans/1
  # DELETE /karyawans/1.json
  def destroy
    @karyawan.destroy
    respond_to do |format|
      format.html { redirect_to karyawans_url, notice: 'Karyawan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_karyawan
      @karyawan = Karyawan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def karyawan_params
      params.require(:karyawan).permit(:nama, :pendidikan_id, :posisi_id)
    end
end

app/controllers/pendidikans_controller.rb
class PendidikansController < ApplicationController
  before_action :set_pendidikan, only: [:show, :edit, :update, :destroy]

  # GET /pendidikans
  # GET /pendidikans.json
  def index
    @pendidikans = Pendidikan.all
  end

  # GET /pendidikans/1
  # GET /pendidikans/1.json
  def show
  end

  # GET /pendidikans/new
  def new
    @pendidikan = Pendidikan.new
  end

  # GET /pendidikans/1/edit
  def edit
  end

  # POST /pendidikans
  # POST /pendidikans.json
  def create
    @pendidikan = Pendidikan.new(pendidikan_params)

    respond_to do |format|
      if @pendidikan.save
        format.html { redirect_to @pendidikan, notice: 'Pendidikan was successfully created.' }
        format.json { render :show, status: :created, location: @pendidikan }
      else
        format.html { render :new }
        format.json { render json: @pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pendidikans/1
  # PATCH/PUT /pendidikans/1.json
  def update
    respond_to do |format|
      if @pendidikan.update(pendidikan_params)
        format.html { redirect_to @pendidikan, notice: 'Pendidikan was successfully updated.' }
        format.json { render :show, status: :ok, location: @pendidikan }
      else
        format.html { render :edit }
        format.json { render json: @pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pendidikans/1
  # DELETE /pendidikans/1.json
  def destroy
    @pendidikan.destroy
    respond_to do |format|
      format.html { redirect_to pendidikans_url, notice: 'Pendidikan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pendidikan
      @pendidikan = Pendidikan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pendidikan_params
      params.require(:pendidikan).permit(:pendidikan_terakhir)
    end
end

app/controllers/posisis_controller.rb
class PosisisController < ApplicationController
  before_action :set_posisi, only: [:show, :edit, :update, :destroy]

  # GET /posisis
  # GET /posisis.json
  def index
    @posisis = Posisi.all
  end

  # GET /posisis/1
  # GET /posisis/1.json
  def show
  end

  # GET /posisis/new
  def new
    @posisi = Posisi.new
  end

  # GET /posisis/1/edit
  def edit
  end

  # POST /posisis
  # POST /posisis.json
  def create
    @posisi = Posisi.new(posisi_params)

    respond_to do |format|
      if @posisi.save
        format.html { redirect_to @posisi, notice: 'Posisi was successfully created.' }
        format.json { render :show, status: :created, location: @posisi }
      else
        format.html { render :new }
        format.json { render json: @posisi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posisis/1
  # PATCH/PUT /posisis/1.json
  def update
    respond_to do |format|
      if @posisi.update(posisi_params)
        format.html { redirect_to @posisi, notice: 'Posisi was successfully updated.' }
        format.json { render :show, status: :ok, location: @posisi }
      else
        format.html { render :edit }
        format.json { render json: @posisi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posisis/1
  # DELETE /posisis/1.json
  def destroy
    @posisi.destroy
    respond_to do |format|
      format.html { redirect_to posisis_url, notice: 'Posisi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posisi
      @posisi = Posisi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def posisi_params
      params.require(:posisi).permit(:posisi)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/karyawans_helper.rb
module KaryawansHelper
end

app/helpers/pendidikans_helper.rb
module PendidikansHelper
end

app/helpers/posisis_helper.rb
module PosisisHelper
end

app/views/karyawans/_form.html.erb
<%= form_with(model: karyawan, local: true) do |form| %>
<% if karyawan.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(karyawan.errors.count, "error") %> prohibited this karyawan from being saved:</h2>

    <ul>
        <% karyawan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :nama %>
    <%= form.text_field :nama %>
</div>

<div class="field">
    <%= form.label :pendidikan_id %>
    <%= form.number_field :pendidikan_id %>
</div>

<div class="field">
    <%= form.label :posisi_id %>
    <%= form.number_field :posisi_id %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

app/views/karyawans/edit.html.erb
<h1>Editing Karyawan</h1>

<%= render 'form', karyawan: @karyawan %>

<%= link_to 'Show', @karyawan %> |
<%= link_to 'Back', karyawans_path %>

app/views/karyawans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Karyawan</h1>
<%= link_to 'Tambah Karyawan', new_karyawan_path %>
<table class="responsive-table red lighten-4">
    <thead>
        <tr>
            <th>Nama</th>
            <th>Pendidikan</th>
            <th>Posisi</th>
            <th colspan="3">Aksi</th>
        </tr>
    </thead>

    <tbody>
        <% @karyawans.each do |karyawan| %>
        <tr>
            <td><%= karyawan.nama %></td>
            <td><%= karyawan.pendidikan.pendidikan_terakhir %></td>
            <td><%= karyawan.posisi.posisi %></td>
            <td><%= link_to 'Show', karyawan %></td>
            <td><%= link_to 'Edit', edit_karyawan_path(karyawan) %></td>
            <td><%= link_to 'Destroy', karyawan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

app/views/karyawans/new.html.erb
<h1>New Karyawan</h1>

<%= render 'form', karyawan: @karyawan %>

<%= link_to 'Back', karyawans_path %>

app/views/karyawans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @karyawan.nama %>
</p>

<p>
  <strong>Pendidikan:</strong>
  <%= @karyawan.pendidikan_id %>
</p>

<p>
  <strong>Posisi:</strong>
  <%= @karyawan.posisi_id %>
</p>

<%= link_to 'Edit', edit_karyawan_path(@karyawan) %> |
<%= link_to 'Back', karyawans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Data Karyawan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>


<style>
    body {
        margin: 0;
        padding: 0;
        height: 1200px
    }


    .jumbotron {
        background-color: red;
        background-size: cover;
        background-attachment: fixed;
        width: 100%;
        height: 500px;
    }



    .display-4 {
        margin-top: 10%;
    }


    th,
    h1,
    h2,
    td,
    p {

        color: black;
        text-shadow: 0 1px 0 #ccc,
            0 2px 0 #c9c9c9,
            0 3px 0 #bbb,
            0 4px 0 #b9b9b9,
            0 5px 0 #aaa,
            0 6px 1px rgba(0, 0, 0, .1),
            0 0 5px rgba(0, 0, 0, .1),
            0 1px 3px rgba(0, 0, 0, .3),
            0 3px 5px rgba(0, 0, 0, .2),
            0 5px 10px rgba(0, 0, 0, .25),
            0 10px 10px rgba(0, 0, 0, .2),
            0 20px 20px rgba(0, 0, 0, .15);
    }
</style>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
     <div  class="nav-item nav-link "><%=  link_to 'Karyawan', karyawans_path %></div>
      <div  class="nav-item nav-link "><%=  link_to 'Pendidikan', pendidikans_path %></div>
      <div  class="nav-item nav-link "><%=  link_to 'Posisi', posisis_path %></div>
 
  </div>
</nav>



    <div class="jumbotron">
        <h1 class="display-4" style="text-align:center;">Data Karyawan</h1>


    </div>




    <div class="container">
        <div class="row">



            <div class="col-12">
                <%= yield %>
            </div>
        </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>

</html>

app/views/pendidikans/_form.html.erb
<%= form_with(model: pendidikan, local: true) do |form| %>
  <% if pendidikan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pendidikan.errors.count, "error") %> prohibited this pendidikan from being saved:</h2>

      <ul>
        <% pendidikan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pendidikan_terakhir %>
    <%= form.text_field :pendidikan_terakhir %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pendidikans/edit.html.erb
<h1>Editing Pendidikan</h1>

<%= render 'form', pendidikan: @pendidikan %>

<%= link_to 'Show', @pendidikan %> |
<%= link_to 'Back', pendidikans_path %>

app/views/pendidikans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pendidikan</h1>
<%= link_to 'Tambah Pendidikan', new_pendidikan_path %>
<table class="responsive-table  green accent-2">
    <thead>
        <tr>
            <th>Pendidikan terakhir</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @pendidikans.each do |pendidikan| %>
        <tr>
            <td><%= pendidikan.pendidikan_terakhir %></td>
            <td><%= link_to 'Show', pendidikan %></td>
            <td><%= link_to 'Edit', edit_pendidikan_path(pendidikan) %></td>
            <td><%= link_to 'Destroy', pendidikan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

app/views/pendidikans/new.html.erb
<h1>New Pendidikan</h1>

<%= render 'form', pendidikan: @pendidikan %>

<%= link_to 'Back', pendidikans_path %>

app/views/pendidikans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pendidikan terakhir:</strong>
  <%= @pendidikan.pendidikan_terakhir %>
</p>

<%= link_to 'Edit', edit_pendidikan_path(@pendidikan) %> |
<%= link_to 'Back', pendidikans_path %>

app/views/posisis/_form.html.erb
<%= form_with(model: posisi, local: true) do |form| %>
  <% if posisi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posisi.errors.count, "error") %> prohibited this posisi from being saved:</h2>

      <ul>
        <% posisi.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :posisi %>
    <%= form.text_field :posisi %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posisis/edit.html.erb
<h1>Editing Posisi</h1>

<%= render 'form', posisi: @posisi %>

<%= link_to 'Show', @posisi %> |
<%= link_to 'Back', posisis_path %>

app/views/posisis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posisi</h1>
<%= link_to 'Tambah Posisi', new_posisi_path %>
<table class="responsive-table blue lighten-5">
    <thead>
        <tr>
            <th>Posisi</th>
            <th colspan="3">Aksi</th>


        </tr>
    </thead>

    <tbody>
        <% @posisis.each do |posisi| %>
        <tr>
            <td><%= posisi.posisi %></td>

            <td><%= link_to 'Show', posisi %></td>
            <td><%= link_to 'Edit', edit_posisi_path(posisi) %></td>
            <td><%= link_to 'Destroy', posisi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

app/views/posisis/new.html.erb
<h1>New Posisi</h1>

<%= render 'form', posisi: @posisi %>

<%= link_to 'Back', posisis_path %>

app/views/posisis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Posisi:</strong>
  <%= @posisi.posisi %>
</p>

<%= link_to 'Edit', edit_posisi_path(@posisi) %> |
<%= link_to 'Back', posisis_path %>